services:
  app:
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres:9.4
    env_file: .env
    restart: always
    environment:
      - POSTGRES_USER=graphql
      - POSTGRES_PASSWORD=graphql
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: